# Environment settings
export PATH="/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin:/usr/local/sbin:/opt/bin:/opt/sbin"
export EDITOR="/usr/bin/vim"
export VISUAL="/usr/bin/vim"
export MANPATH="/usr/share/man"
export PAGER="/usr/bin/less -R"

# Set the prompt
export PS1="[\u@\h \W]\\$ "

# Some useful aliases
alias l.='ls -d .* --color=auto'
alias ll='ls -l --color=auto'
alias ls='ls --color=auto'
alias mv='mv -i'
alias cp='cp -i'
alias rm='rm -i'

# Our locale setup
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8

# Enhancements for bash itself
HISTTIMEFORMAT="%c "
HISTCONTROL=ignoredups:erasedups
HISTSIZE=10000
HISTFILESIZE=10000
shopt -s histappend

