# $Id$

# Environment settings
export PATH="/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin:/usr/local/sbin:/opt/bin:/opt/sbin"
export EDITOR="/bin/vi"
export VISUAL="/bin/vi"
export MANPATH="/usr/share/man"
export PAGER="/usr/bin/less -R"

# Set the prompt
export PS1="[\u@\h \W]\\$ "

# Some useful aliases
alias l.='ls -d .* --color=auto'
alias ll='ls -l --color=auto'
alias ls='ls --color=auto'
alias mv='mv -i'
alias cp='cp -i'
alias rm='rm -i'

